[tool.poetry]
name = "cloudflare-dyndns"
version = "0.0.2"
description = "A terrible dynamic DNS updater for cloudflare"
authors = [
    "James Hodgkinson <james@terminaloutcomes.com>",
]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.4"
loguru = "^0.7.3"
pydantic = "^2.11"
backoff = "^2.2.1"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
cloudflare-dyndns = "cloudflare_dyndns.__main__:main"

[tool.poetry.group.dev.dependencies]
mypy = "^1.16.0"
ruff = "^0.11.13"
pytest = "^8.4.0"
black = "^25.1.0"
types-requests = "^2.32.4.20250611"

[build-system]
requires = [
    "poetry-core>=1.0.0",
]
build-backend = "poetry.core.masonry.api"

[project]
name = "cloudflare-dyndns"
description = "A terrible dynamic DNS updater for cloudflare"
license = "MIT"
version = "0.0.2"
authors = [
    { name = "James Hodgkinson", email = "james@terminaloutcomes.com" },
]
