[tool.poetry]
name = "cloudflare-dyndns"
version = "0.0.2"
description = "A terrible dynamic DNS updater for cloudflare"
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.27.1"
loguru = "^0.7.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
